# Generated by Django 4.2.7 on 2024-01-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=0, max_length=6, verbose_name='секретный ключ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
    ]
