# Generated by Django 4.2.7 on 2024-01-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Опубликован'), (False, 'Не опубликован')], default=False, verbose_name='Статус публикации'),
        ),
    ]
