# Generated by Django 4.2.7 on 2024-01-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish product'), ('change_product_description', 'Can change product_description'), ('change_category', 'Can change category of the product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
